### ISSUE TITLE
build errors on Android and on iOS

### ISSUE THREAD

**Issue by Zvika88** [chemerisuk/cordova-plugin-firebase-authentication#18]
The cordova plugin was aded without errors (cocoapods was installed and setup during the process). However the following errors occur when trying to build an app:

Android:
Could not get unknown property 'FIREBASE_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

iOS:
ld: warning: directory not found for option ‘-L/Users/…/Debug-iphoneos/GTMSessionFetcher’
ld: warning: directory not found for option ‘-L/Users/…/Debug-iphoneos/GoogleToolboxForMac’
ld: warning: directory not found for option ‘-L/Users/…/Debug-iphoneos/nanopb’
ld: library not found for -lGTMSessionFetcher
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chemerisuk** [comment]
Have you tried to set variable:

```
cordova plugin add cordova-plugin-firebase-authentication --variable FIREBASE_VERSION=15.0.+
```

**Comment by nightwolf13** [comment]
The same..
Here is error message:
" problem occurred evaluating root project 'android'.
> Could not get unknown property 'FIREBASE_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler."

Looks like it cannot replace FIREBASE_VERSION property in build.gradle file..

Maybe it's connected to cordova version?.. I have 7.0.1

**Comment by joshorvis** [comment]
I've got the same message as nightwolf13.   Tried setting the variable per chemerisuk's suggestions, no effect.  

If I remove this plugin, it builds successfully.

**Comment by andreszs** [comment]
**Same error** here with cordova 6.5.0 and cordova-android 6.3.0.

> Could not get unknown property 'FIREBASE_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler."

Please let us know if this can be fixed somehow because the Firebase plugin is very promising, but you can't force developers to certain CLI version because the plugin doesn't work. Please try to fix it and add a PayPal donation button to your `README `so users can contribute.

Build is successful only with cordova 7.1.0 after applying [this pull request](https://github.com/chemerisuk/cordova-plugin-firebase-authentication/pull/28).
