### ISSUE TITLE
Make onAuthStateChanged(callback) a real listener

### ISSUE THREAD

**Issue by Hirbod** [chemerisuk/cordova-plugin-firebase-authentication#22]
Currently, calling a window.location.reload() will cause the callback be registered multiple times. There is also no way to remove a listener.

**Comment by andreszs** [comment]
If you really need to reload the webview (why?) you could use localStorage to store a flag telling your app that the `onAuthStateChanged()` method has or hasn't been already invoked, in order to prevent further re-registrations.

```javascript
if(localStorage.getItem('AuthStateChanged') === null || parseInt(localStorage.getItem('AuthStateChanged') === 0){
    // Not registered, do it now
    cordova.plugins.firebase.auth.onAuthStateChanged(/* ... */);
    localStorage.setItem('AuthStateChanged', '1');
}else{
    // Already registered, skip that
}
```

Every time the app is initialized, set it to `0` on the deviceReady() event to ensure you register at least once, of course.

**Comment by Hirbod** [comment]
It's sometimes invoked trough the Ionic WKWebview Plugin.

**Comment by Hirbod** [comment]
This plugin should override existing listeners.
