### ISSUE TITLE
onAuthStateChanged not work on ios

### ISSUE THREAD

**Issue by alaanasreng** [chemerisuk/cordova-plugin-firebase-authentication#48]
Hello Sir,

onAuthStateChanged not work on ios??

Best Regards

**Comment by JavierPAYTEF** [comment]
This doesn't work in iOS because the method is not implemented in the code, I don't know if it's possible or not to implement it. This wouldn't be that bad if it was mentioned in the documentation, I don't quite understand why it's not.

Actually if you try calling that in iOS you get this:

> 2019-03-02 02:13:33.791086-0300 App[4898:93697] ERROR: Method 'setAuthStateChanged:' not defined in Plugin 'FirebaseAuthentication'
> 2019-03-02 02:13:33.791162-0300 App[4898:93697] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["FirebaseAuthentication1147466081","FirebaseAuthentication","setAuthStateChanged",[false]]

It would be nice if this was explained anywhere in the documentation to avoid future problems.

**Comment by JavierPAYTEF** [comment]
I'm just realizing this is a big deal for this plugin. Without this, and because the plugin doesn't have any "getCurrentUser()" method, you have no way of getting the data of the currently logged user unless you previously stored it somewhere at login.
iOS documentation actually shows a similar method for registering listener. https://firebase.google.com/docs/auth/ios/manage-users?hl=es-419
```Objective-C
self.handle = [[FIRAuth auth]
    addAuthStateDidChangeListener:^(FIRAuth *_Nonnull auth, FIRUser *_Nullable user) {
      // ...
    }];
```
Was this not implemented for a particular reason?

**Comment by JavierPAYTEF** [comment]
In case you still need it I made a pull request to fix this: https://github.com/chemerisuk/cordova-plugin-firebase-authentication/pull/54

**Comment by chemerisuk** [comment]
@alaanasreng Please let me know if v1.1.0 works for you.
