### ISSUE TITLE
Identify the user to firebase for database handling

### ISSUE THREAD

**Issue by vorkapps** [chemerisuk/cordova-plugin-firebase-authentication#94]
Hi,
I was using the firebase auth functions to authenticate the user, which was working fine on Android, but the reCaptcha was not working on iOS. So after searching I found your plugin, and switched to it for authentication.
So I authenticate the user via phone authentication. The SMS is sent properly and verification completes successfully.
I then do database queries using the firebase plugin, which fail because the user is not "identified" in that firebase instance. So I tried using getIdToken() to retrieve the token from this plugin, and use auth.signInWithCustomToken() passing the token retrieved, however I get:    {code: "auth/invalid-custom-token"
message: "The custom token format is incorrect. Please check the documentation."}
Any guidance on how the user can be identified to the firebase instance so that database queries that require the user to be authenticated can be executed successfully?
Thank you

**Comment by NikethanR** [comment]
Hi,
If you logged the user in using this plugin, this authentication wont be valid inside the javascript code to make use of firebase.database()
You need to do a mix of both this plugin and javascript auth
This involves tweaking the plugin, following is for android
Make sure to edit the files that are under platforms/android/app
1) FirebaseAuthentication.js - Add a new method getSmsCode
`
verifyPhoneNumber: function(phoneNumber, timeoutMillis) {
        return new Promise(function(resolve, reject) {
            exec(resolve, reject, PLUGIN_NAME, "verifyPhoneNumber", [phoneNumber, timeoutMillis]);
        })
    },
    getSmsCode: function() {
        return new Promise(function(resolve, reject) {
            exec(resolve, reject, PLUGIN_NAME, "getSmsCode",[]);
        })
    },
`
2) Add correspoding cordova method to FirebaseAuthenticationPlugin.java 
`
public class FirebaseAuthenticationPlugin extends ReflectiveCordovaPlugin implements AuthStateListener {
....
    private String smsCode = "";
    private CallbackContext smsCallback;
....

@CordovaMethod
    private void getSmsCode(final CallbackContext callbackContext) {
        this.smsCallback = callbackContext;
        if(this.smsCode!=null && !this.smsCode.isEmpty()) {
            callbackContext.success(smsCode);
        }
    }

@CordovaMethod
    private void verifyPhoneNumber(String phoneNumber, long timeoutMillis, final CallbackContext callbackContext) {
        phoneAuthProvider.verifyPhoneNumber(phoneNumber, timeoutMillis, MILLISECONDS, cordova.getActivity(),
                new PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
                    @Override
                    public void onVerificationCompleted(PhoneAuthCredential credential) {
                        // following line removed to avoid auto retrieval login
                        // signInWithPhoneCredential(credential);
                        if(credential!=null) {
                            smsCode = credential.getSmsCode();
                            if(smsCode!=null && smsCallback!=null) {
                               //pass the code back to javascript
                                smsCallback.success(smsCode);
                            } 
                        }
                    }

                    @Override
                    public void onCodeSent(String verificationId, PhoneAuthProvider.ForceResendingToken forceResendingToken) {
                        callbackContext.success(verificationId);
                    }

                    @Override
                    public void onVerificationFailed(FirebaseException e) {
                        callbackContext.error(e.getMessage());
                    }
                }
        );
    }
}
`
3)Now in your js file
`
        cordova.plugins.firebase.auth.verifyPhoneNumber("+91"+mobNum, 30000)
        .then(function(verificationString) {
            window.verificationId = verificationString;
            cordova.plugins.firebase.auth.getSmsCode().then(
                function (code) {
                    tcode = code;
                   //Auto retrieval case
                    submitCode();
                }
            );
        })
`
4)Once you have verificationid and code(either by maual entry or auto retrieval)

`
        const credential = firebase.auth.PhoneAuthProvider.credential(
            verificationId,
            code
        );
        firebase.auth()
            .signInAndRetrieveDataWithCredential(credential)
            .then((result) => {
                // login success
            })
`
Manual entry of the otp - handled
Auto retrieval of the otp - handled
instant verfication case - I dont think you should worry about this case because at the end you are not logging in the user using the native apis
If you log the user in this way you should be able to make use of firebase.database() namespace and the authentication will hold with userid based security rules

**Comment by vorkapps** [comment]
@NikethanR thank you VERY much for the elaborate response. This looks like it will solve the issue and I tried to apply it, however inside the platforms/android/app structure I could only find the .js file. The file FirebaseAuthenticationPlugin.java can only be found in node_modules & plugins subfolders in the src folder structure. I made the suggested changes everywhere, but the verifyphonenumber().then() still is not hit..... Any ideas on what I'm doing wrong?

Again many thanks!

**Comment by vorkapps** [comment]
Just a sidenote: I'm using Ionic and have installed and used the plugin according to the documentation here: https://ionicframework.com/docs/native/firebase-authentication

**Comment by NikethanR** [comment]
Unfortunately that solution only works for 2 cases - manual entry of otp, and auto detection of otp, its doesnt work for instants verification when firebase doesnot send otp 
After lots of searching online Instant verification cannot be disabled at all
I changed my authentication process
I use this plugin and login as it is and then get the id token
`cordova.plugins.firebase.auth.getIdToken().then(function(idToken) {
           //submit this id token to server
          }).catch(function (e) {
});`

On the server side validate the idtoken and create a custom token and return it back to client
your server should be linked to a service account and should use firebase admin sdk 
'return admin.auth().verifyIdToken(idToken)
            .then(function (decodedToken) {
                var uid = decodedToken.uid;
                admin.auth().createCustomToken(uid)
                    .then(function(customToken) {
                        //return this customToken to client
                    })
            })' 

Once you get the custom token on client, login using it
`firebase.auth().signInWithCustomToken(customToken)
      .catch(function (error) {
        
      });`

Due to the the extra calls, login process seems to take 3 times more time than usual, but i couldnt find any other workaround for this

**Comment by vorkapps** [comment]
aaaaaaaaaaaaaaaaaaaaaaand Just like that, it works perfectly on Android :)  Now let me see if iOS is happy about that too :)
MANY thanks @NikethanR  !!!
